source 'http://rubygems.org'

gem 'rails', '~> 6.1'
gem 'mailboxer', :path => '../../'
gem 'factory_girl'
gem 'listen'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem "sqlite3", :platform => [:ruby, :mswin, :mingw]
gem "jdbc-sqlite3", :platform => :jruby
