# frozen_string_literal: true

source 'http://rubygems.org'

gem 'factory_girl'
gem 'listen'
gem 'mailboxer', path: '../../'
gem 'rails', '~> 6.1'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'jdbc-sqlite3', platform: :jruby
gem 'sqlite3', platform: %i[ruby mswin mingw]
