# frozen_string_literal: true

source 'http://rubygems.org'

gem 'factory_bot_rails'
gem 'listen'
gem 'mailboxer', path: '../../'
gem 'rails', '~> 7.1.3', '>= 7.1.3.3'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'jdbc-sqlite3', platform: :jruby
gem 'sqlite3', '~> 1.4', platform: %i[ruby mswin mingw]
